apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-core" 
spec:
  capacity:
    storage: "500Gi" 
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "disk-blockchains" 
